import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Function to create request
const createRequest = (url) => ({ url });

// Create the API slice using RTK Query
export const appointmentApi = createApi({
  reducerPath: "appointmentApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const doctor_token = localStorage.getItem("doctor_token");
      if (doctor_token) {
        headers.set("Authorization", `Bearer ${doctor_token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAppointments: builder.query({
      query: (params) => ({
        url: "/admin/appointment",
        method: "GET",
        params: {
          page: params?.page || 1,
          limit: params?.limit || 10,
          doctorId: params?.doctorId,
          clinicId: params?.clinicId,
          fromDate: params?.fromDate,
          toDate: params?.toDate,
          isBooked: params?.isBooked,
          consultationType: params?.consultationType,
          orderBy: params?.orderBy || 'date',
          orderDirection: params?.orderDirection || 'asc'
        }
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const { useGetAppointmentsQuery } = appointmentApi; 