import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithRedirect } from './baseQuery';

// Function to create request
const createRequest = (url) => ({ url });

// Create the API slice using RTK Query
export const appointmentApi = createApi({
  reducerPath: "appointmentApi",
  baseQuery: baseQueryWithRedirect,

  endpoints: (builder) => ({
    getAppointments: builder.query({
      query: (params) => ({
        url: "/admin/appointment",
        method: "GET",
        params: {
          page: params?.page || 1,
          limit: params?.limit || 10,
          doctorId: params?.doctorId,
          clinicId: params?.clinicId,
          fromDate: params?.fromDate,
          toDate: params?.toDate,
          isBooked: params?.isBooked,
          consultationType: params?.consultationType,
          orderBy: params?.orderBy || 'date',
          orderDirection: params?.orderDirection || 'asc'
        }
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const { useGetAppointmentsQuery } = appointmentApi; 