import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithRedirect } from './baseQuery';

// Create the API slice using RTK Query
export const specializationApi = createApi({
  reducerPath: "specializationApi",
  baseQuery: baseQueryWithRedirect,

  endpoints: (builder) => ({
    getSpecializations: builder.query({
      query: (params) => ({
        url: '/admin/doctor-specializations',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
    getSpecialization: builder.query({
      query: (id) => `/admin/doctor-specializations/${id}`,
    }),
    addSpecialization: builder.mutation({
      query: (data) => ({
        url: "/admin/doctor-specializations",
        method: "POST",
        body: data,
      }),
    }),
    updateSpecialization: builder.mutation({
      query: ({ id, data }) => ({
        url: `/admin/doctor-specializations/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteSpecialization: builder.mutation({
      query: (id) => ({
        url: `/admin/doctor-specializations/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetSpecializationsQuery,
  useGetSpecializationQuery,
  useAddSpecializationMutation,
  useUpdateSpecializationMutation,
  useDeleteSpecializationMutation,
} = specializationApi;

