import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithRedirect } from './baseQuery';

// Create the API slice using RTK Query
export const filesApi = createApi({
  reducerPath: "filesApi",
  baseQuery: baseQueryWithRedirect,

  endpoints: (builder) => ({
   
    addFile: builder.mutation({
      query: (data) => ({
        url: "/shared/upload",
        method: "POST",
        body: data,
      }),
    }),
    addFile: builder.mutation({
      query: (data) => ({
        url: "/shared/upload",
        method: "POST",
        body: data,
      }),
    }),
    addFiles: builder.mutation({
      query: (data) => ({
        url: "shared/upload/multiple",
        method: "POST",
        body: data,
      }),
    }),
    
  }),
});

// Export hooks generated by the API service
export const {
    useAddFileMutation,
    useAddFilesMutation
} = filesApi;
